"""all

Revision ID: 1f873aa5a6cf
Revises: a249859dfcdd
Create Date: 2022-06-19 19:22:58.951259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f873aa5a6cf'
down_revision = 'a249859dfcdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('LastName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('FirstName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('EmailAddress', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='User_pkey')
    )
    # ### end Alembic commands ###
